import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import App from "./App";
import "react-toastify/dist/ReactToastify.css";
import "animate.css/animate.min.css";
import AuthMiddleware from "@/components/Middlewares/AuthMiddleware";
import {Toastify} from "@/components/UI";
import AppSetup from "./AppSetup";
import Audio from "@/components/Audio";
import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "next-intl/server";
import {notFound} from "next/navigation";
import {routing} from "@/i18n/routing";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "PlayTime | Time to play & relax",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params: {locale},
}: Readonly<{
    children: React.ReactNode;
    params: {locale: string};
}>) {
    // Ensure that the incoming `locale` is valid
    if (!routing.locales.includes(locale as any)) {
        notFound();
    }

    // Providing all messages to the client
    // side is the easiest way to get started
    const messages = await getMessages();

    return (
        <html data-theme="myLightTheme" lang={locale}>
            <body className={`${inter.className} antialiased`}>
                <NextIntlClientProvider messages={messages}>
                    <StoreProvider>
                        <AuthMiddleware>
                            <AppSetup>
                                <Audio />
                                <App>{children}</App>
                            </AppSetup>
                        </AuthMiddleware>
                        <Toastify />
                    </StoreProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
